layout_spectrum: 0.125448
typography_spectrum: 0.3010753
color:
  saturation: 0.375966
  lightness: 0.269997
  brandStrength: 0.6271984
  rhythmicContrast: 0.1064651
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Matt Cluett
