name: Matt Cluett
favicon: null
layout_spectrum: 0.125448
typography_spectrum: 0.3010753
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#7ab0b8'
    - '#223c4b'
    - '#e4c479'
    - '#a1461c'
  brandStrength: 0.6271984
  lightness: 0.269997
  saturation: 0.375966
  rhythmicContrast: 1
purpose: []
