typography_spectrum: 0.7921147
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.2114695
title: null
purpose: []
color:
  saturation: 0.7670251
  brandStrength: 0.3125
  rhythmicContrast: 0.8405018
  brandColors:
    - '#040404'
    - '#7ab0b8'
    - '#223c4b'
    - '#e4c479'
    - '#a1461c'
  lightness: 0.5215054
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Matt Cluett
